# Generated by Django 2.2.1 on 2019-05-03 21:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('internal', '0003_preferences_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Preferences',
            new_name='Preference',
        ),
    ]
