# Generated by Django 2.2.1 on 2019-05-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0008_auto_20190509_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
