# Generated by Django 2.2.1 on 2019-05-13 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0009_link_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
