# Generated by Django 2.2.1 on 2019-05-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0011_auto_20190513_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='text',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
