# Generated by Django 2.2.1 on 2019-05-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0013_link_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='order',
            field=models.PositiveSmallIntegerField(null=True, unique=True),
        ),
    ]
