# Generated by Django 2.2.1 on 2019-05-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0014_link_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='background_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='preference',
            name='profile_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
