# Generated by Django 2.2.1 on 2019-05-21 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0015_igtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ig_token', to=settings.AUTH_USER_MODEL),
        ),
    ]
