# Generated by Django 2.2.1 on 2019-06-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0015_auto_20190527_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='order',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
