# Generated by Django 2.2.1 on 2019-05-21 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0016_auto_20190521_0253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='igtoken',
            options={'verbose_name': 'Instagram Token', 'verbose_name_plural': 'Instagram Tokens'},
        ),
    ]
