# Generated by Django 2.2.1 on 2019-05-28 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0017_auto_20190521_0332'),
        ('internal', '0015_auto_20190527_2332'),
    ]

    operations = [
    ]
