# Generated by Django 2.2.1 on 2019-05-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0018_merge_20190528_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='order',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
