# Generated by Django 2.2.2 on 2019-06-07 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0019_auto_20190528_1716'),
        ('internal', '0016_auto_20190604_0025'),
    ]

    operations = [
    ]
