# Generated by Django 2.2.2 on 2019-06-05 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0016_auto_20190604_0025'),
        ('internal', '0019_auto_20190528_1716'),
    ]

    operations = [
    ]
