# Generated by Django 2.2.2 on 2019-06-06 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0020_merge_20190605_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internal.Link'),
        ),
    ]
