# Generated by Django 2.2.1 on 2019-06-06 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0020_merge_20190606_0804'),
        ('internal', '0021_auto_20190606_0717'),
    ]

    operations = [
    ]
