# Generated by Django 2.2.2 on 2019-06-07 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0021_auto_20190607_0626'),
        ('internal', '0020_merge_20190607_0607'),
    ]

    operations = [
    ]
