# Generated by Django 2.2.1 on 2019-06-07 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0023_auto_20190607_0132'),
        ('internal', '0022_merge_20190607_1753'),
    ]

    operations = [
    ]
